---
kind: pipeline
name: default

steps:
    - name: dummy
      image: alpine:3
      pull: always
      commands:     
      - echo "hello"
      
trigger:
  branch:
  - master  

trigger:
  event:
  - pull_request
  - push
---
kind: signature
hmac: 4cda5542fa43796175f5abe9f8510deb23677fe8d4578e8c6096625d28705d49

...
