name: Build

on:
  push:
    branches:
    - "master"
    - "min/build-image"
  workflow_call:
    secrets:
      # Secrets used to build
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GH_BOT_DEPLOY_KEY:
        required: true

jobs:
  hash:
    runs-on: ubuntu-latest
    outputs:
      HASH: ${{ steps.hash.outputs.short }}
    steps:
      - id: hash
        uses: pr-mpt/actions-commit-hash@v2
        with:
          # NOTE: since this workflow is only triggered by `push` event
          # github.sha have correct commit sha
          commit: ${{ github.sha }}
  stack_image:
    runs-on: ubuntu-latest
    outputs:
      LIBS10: ${{ steps.image.outputs.IMAGE_LIBS10 }}
      LIBS11: ${{ steps.image.outputs.IMAGE_LIBS11 }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: signalwire/libks
          ref: master
          path: /__w/signalwire-c/signalwire-c/libks
      - run: |
          cd /__w/signalwire-c/signalwire-c/libks
          export LIBKS_SHA=$(git rev-parse --short HEAD);
          export IMAGE_LIBS10="signalwire/freeswitch-libs:libks-libs10-$LIBKS_SHA"
          export IMAGE_LIBS11="signalwire/freeswitch-libs:libks-libs11-$LIBKS_SHA"
          echo "IMAGE_LIBS10=$IMAGE_LIBS10" >> $GITHUB_OUTPUT
          echo "IMAGE_LIBS11=$IMAGE_LIBS11" >> $GITHUB_OUTPUT
        id: image
  build:
    needs: [hash,stack_image]
    strategy:
      matrix:
        include:
          - tag: signalwire-c-libs10-${{ needs.hash.outputs.HASH }}
            baseimage: signalwire/freeswitch-base:debian-10
            libks_image: ${{ needs.stack_image.outputs.LIBS10 }}
          - tag: libks-libs11-${{ needs.hash.outputs.HASH }}
            baseimage: signalwire/freeswitch-base:debian-11
            libks_image: ${{ needs.stack_image.outputs.LIBS11 }}     
    name: "build signalwire-c"
    uses: signalwire/actions-template/.github/workflows/ci-build.yml@main
    with:
      CONTAINER_SCAN: true
      CONTAINER_TEST: false
      PROJECT_NAME: "freeswitch-libs"
      FILE: ./Dockerfile
      PUSH: true
      RUNNER: ubuntu-latest
      TAG: ${{ matrix.tag }}
      BUILD_ARGS: |
        BASEIMAGE=${{ matrix.baseimage }}
        LIBKS_IMAGE=${{ matrix.libks_image }}
    secrets: inherit